services:
  backend:
    build:
      context: ./backend
    ports: 
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: ./frontend
    ports:
     - "3000:80"
